spring.application.name=tasks

#Clever cloud
spring.datasource.url=jdbc:mysql://uxcgjtf3mgdop4r0:4bTGfo0BoMUtVjj3IMri@biadgahphjark3kps12g-mysql.services.clever-cloud.com:3306/biadgahphjark3kps12g
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000

#Local DB
#spring.datasource.url=jdbc:mysql://localhost:3306/task_crud?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
#spring.datasource.username=kodilla
#spring.datasource.password=kodilla

spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

#Trello
trello.api.endpoint.prod=https://api.trello.com/1
trello.app.key=71924e9ad01b180dbbf5f39acf00cc5c
trello.app.token=ATTA0c8e096ca06b0f316fc6174379a475d79e02d8ddf0aa4cb6cadbf554fe627069088902F4
trello.app.username=artur.flisek@gmail.com

# EMAIL CONFIGURATION
spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
admin.mail=artur.flisek@gmail.com
domain.mail=hello@demomailtrap.co
